console.log("Hello Winc Academy");
let name = "Daniël";
console.log(name);
let uitkomst1 = 4 + 4;
console.log(uitkomst1);
let uitkomst2 = "4" + "4";
console.log(uitkomst2);
console.log(2 + 2);
console.log(4 - 2);
console.log(2 * 3);
console.log(12 % 100);
let age = "33";
console.log(typeof age);